import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { PROTOCOL_CAPABILITIES } from '../shared/deployment-capabilities.js';

const root = process.cwd();
const packageJson = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
const runtimeVersion = String(packageJson.version || '').trim();
if (!/^\d+\.\d+\.\d+(?:[-+].*)?$/.test(runtimeVersion)) throw new Error(`Invalid package version: ${runtimeVersion}`);
const modulesDir = path.join(root, 'runtime', 'v2', 'modules');
const outputDir = path.join(root, 'public', 'proxy', 'v2');
const generatedDir = path.join(root, 'functions', 'generated');
const names = (await readdir(modulesDir)).filter(name => name.endsWith('.sh')).sort();
const providers = JSON.parse(await readFile(path.join(root, 'runtime', 'v2', 'providers.json'), 'utf8'));
for (const core of ['xray', 'sing-box', 'naive']) {
  const entries = Object.entries(PROTOCOL_CAPABILITIES).filter(([, capability]) => capability.cores.includes(core));
  providers[core].protocols = entries.map(([protocol]) => protocol);
  providers[core].transports = [...new Set(entries.flatMap(([, capability]) => capability.transports[core] || []))];
}
const chunks = [];
for (const name of names) {
  let source = await readFile(path.join(modulesDir, name), 'utf8');
  source = source.replace(/^#!.*\r?\n/, '').replace(/\r\n/g, '\n').trim();
  chunks.push(`# module: ${name}\n${source}`);
}
const runtime = `#!/bin/sh\n# Generated file. Edit runtime/v2/modules/*.sh instead.\nTSUB_RUNTIME_VERSION='${runtimeVersion}'\n${chunks.join('\n\n')}\n`;
const sha256 = createHash('sha256').update(runtime).digest('hex');
await mkdir(outputDir, { recursive: true });
await mkdir(generatedDir, { recursive: true });
let history = {};
try {
  const previousManifest = JSON.parse(await readFile(path.join(outputDir, 'manifest.json'), 'utf8'));
  history = { ...(previousManifest.history || {}) };
  const previousVersion = String(previousManifest.runtimeVersion || '').trim();
  const previousRuntime = await readFile(path.join(outputDir, 'tsub-proxy.sh'));
  if (previousVersion && previousVersion !== runtimeVersion && /^[0-9A-Za-z._-]+$/.test(previousVersion)
    && previousManifest.runtime?.sha256 === createHash('sha256').update(previousRuntime).digest('hex')) {
    const archiveDir = path.join(outputDir, 'history', previousVersion);
    await mkdir(archiveDir, { recursive: true });
    await writeFile(path.join(archiveDir, 'tsub-proxy.sh'), previousRuntime, { mode: 0o755 });
    history[previousVersion] = {
      path: `/proxy/v2/history/${previousVersion}/tsub-proxy.sh`,
      sha256: previousManifest.runtime.sha256,
      bytes: previousRuntime.byteLength
    };
  }
} catch {}
await writeFile(path.join(outputDir, 'tsub-proxy.sh'), runtime, { mode: 0o755 });
const manifest = { schemaVersion: 2, runtimeVersion, runtime: { path: '/proxy/v2/tsub-proxy.sh', sha256, bytes: Buffer.byteLength(runtime) }, history, providers, cores: { xray: { version: '26.7.28', assets: {} }, 'sing-box': { version: '1.13.15', assets: {} }, naive: { version: '134.0.6998.88-1', assets: {} }, cloudflared: { version: '2026.6.0', assets: {} }, wgcf: { version: '2.2.22', assets: {} }, lego: { version: '4.26.0', assets: {} }, busybox: { version: '1.38.0-musl', assets: {} } } };
await writeFile(path.join(outputDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
await writeFile(path.join(generatedDir, 'runtime-manifest.js'), `// Generated by scripts/build-runtime.mjs\nexport const RUNTIME_MANIFEST = Object.freeze(${JSON.stringify({ version: runtimeVersion, path: '/proxy/v2/tsub-proxy.sh', sha256, bytes: Buffer.byteLength(runtime), history }, null, 2)});\n`);
console.log(`Built TSub Proxy v2 (${Buffer.byteLength(runtime)} bytes, ${sha256})`);
